backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: text}
      - {label: Read Time, name: readTime, widget: number}
      - {label: Image, name: mainImage, widget: image}
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}